### ISSUE TITLE
What are the WebUi projects? 

### ISSUE THREAD

**Issue by punkouter24** [ubhaya/CleanArchitecture.Blazored#34]
WebUi works and I guess that is Blazor + Server right?

WebUi.Client seems to be blazor web assembly right?  How do I get that to work.. run the web assembly AND what else?  

Also is the Maui branch suppose to contains a MAUI project?

**Comment by ubhaya** [comment]
This is not blazor + server. This is new blazor web app concept in .Net 8.

Maui branch still under development. it will contain the MAUI project in future,
