### ISSUE TITLE
Problem with MudBlazor version 

### ISSUE THREAD

**Issue by punkouter24** [ubhaya/CleanArchitecture.Blazored#36]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB4019	The imported project "C:\Users\punko\BuildSettings\CabMud.props" was not found. Confirm that the expression in the Import declaration "..\..\..\..\..\BuildSettings\CabMud.props" is correct, and that the file exists on disk.	WebUi (src\WebUi\WebUi)	C:\Users\punko\Downloads\CabMud\src\WebUi\WebUi\WebUi.csproj	3

**Comment by ubhaya** [comment]
WebUi.csproj there should be a line with `<Import Project="..........\BuildSettings\CabMud.props"/>`. Delete this and it should work.
